/// Flutter icons IngredientIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IngredientIcons
///      fonts:
///       - asset: fonts/IngredientIcons.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class IngredientIcons {
  IngredientIcons._();

  static const _kFontFam = 'IngredientIcons';
  static const String? _kFontPkg = null;

  static const IconData milk = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caramel = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vanilla = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whipped_cream = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ice_cube = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sugar = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
