/// Flutter icons IngredientIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IngredientIcons
///      fonts:
///       - asset: fonts/IngredientIcons.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class IngredientIcons {
  IngredientIcons._();

  static const _kFontFam = 'IngredientIcons';
  static const String? _kFontPkg = null;

  static const IconData water = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sugar = IconData(0xe986, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ice_cube = IconData(0xea0c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData espresso = IconData(0xf0f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hazelnut = IconData(0xf4d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
